"""add archivefile slug

Revision ID: bbd556755d70
Revises: 29b4e3a338ad
Create Date: 2025-03-02 17:50:51.058281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'bbd556755d70'
down_revision: Union[str, None] = '29b4e3a338ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivefile', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False))
    op.alter_column('archivefile', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=40),
               existing_nullable=False)
    op.alter_column('archivefile', 'file_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'archivefile', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'archivefile', type_='unique')
    op.alter_column('archivefile', 'file_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('archivefile', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=40),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('archivefile', 'slug')
    # ### end Alembic commands ###
