"""add DataPath file_type field

Revision ID: b084d745a76b
Revises: e4f7162b7c55
Create Date: 2025-03-04 12:41:50.142289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b084d745a76b'
down_revision: Union[str, None] = 'e4f7162b7c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datapath', sa.Column('file_type', sa.Enum('FINA', name='datafiletype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datapath', 'file_type')
    # ### end Alembic commands ###
