"""add DataPath type and add emonHost path

Revision ID: e4f7162b7c55
Revises: 5451f8a86af7
Create Date: 2025-03-04 11:58:12.308691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f7162b7c55'
down_revision: Union[str, None] = '5451f8a86af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datapath', sa.Column('path_type', sa.Enum('ARCHIVED', 'EMONCMS', name='datapathtype'), nullable=True))
    op.add_column('emonhost', sa.Column('datapath_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'emonhost', 'datapath', ['datapath_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emonhost', type_='foreignkey')
    op.drop_column('emonhost', 'datapath_id')
    op.drop_column('datapath', 'path_type')
    # ### end Alembic commands ###
